version: "3"

services:
  masters_thesis_project:
    build: .
    volumes:
      # mount for development purposes
      - ./:/app
      # custom volumes
      - ~/.cache:/root/.cache
      - ~/.python_history:/root/.python_history
    container_name: masters_thesis_project
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
